version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  redis:
    image: redis
    environment:
      - REDIS_URL=redis://redis:6379

  sidekiq:
    build: .
    volumes:
      - .:/myapp
    links:
      - db
      - redis
    command: sh -c "gem install sidekiq && bundle update sidekiq && bundle exec sidekiq"
    environment:
      - REDIS_URL=redis://redis:6379    

  web:
    build: .
    command: sh -c "gem install rmagick && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
